// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_refresh_token_revoked_at.sql

package database

import (
	"context"
	"database/sql"
)

const updateRefreshTokenRevokedAt = `-- name: UpdateRefreshTokenRevokedAt :exec
UPDATE refresh_tokens
SET revoked_at = $1,
    updated_at = NOW()
WHERE token = $2
`

type UpdateRefreshTokenRevokedAtParams struct {
	RevokedAt sql.NullTime
	Token     string
}

func (q *Queries) UpdateRefreshTokenRevokedAt(ctx context.Context, arg UpdateRefreshTokenRevokedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenRevokedAt, arg.RevokedAt, arg.Token)
	return err
}
