POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
  "body": "I really need a kerfuffle to go to bed sooner, Fornax !"
}

###

GET http://localhost:8080/api/healthz

###

POST http://localhost:8080/api/users
content-type: application/json

{
  "email": "mloneusk@example.co"
}

###

GET http://localhost:8080/admin/metrics

###

POST http://localhost:8080/admin/reset